---
- name: Update apt-get repo and cache
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

- name: Upgrade all apt packages
    apt: upgrade=dist force_apt_get=yes

- name: Install required system packages
  apt:
    pkg:
      - vim
      - wget
      - git
      - bash-completion
      - less
      - htop
      - nano
      - net-tools
      - screen
      - zip
      - unzip
      - dnsutils
      - nmap
      - tar
      - bind9utils 
      - rsync
    state: latest
    update_cache: true


